<?php

namespace NotificationBundle\Tests\Controller;


use Tests\Framework\WebTestCase;

class DefaultControllerTest extends WebTestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function index()
    {

        $this->visit( '/notifications/')
             ->assertResponseOk()
             ->seeText('Monitor page');

    }


}
