services:
#    notification.example:
#        class: NotificationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    notification.cache:
        class: NotificationBundle\Manager\Cache\NotificationCache
        arguments:
            - "@service_container"

    notification.message:
        class: NotificationBundle\Factory\Message

    notification.center:
        class: NotificationBundle\Factory\NotificationCenter

    notification.server:
        class: NotificationBundle\Server\NotificationServer
        arguments:
            - "@service_container"